services:
  - type: web
    name: promobot
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    autoDeploy: true
    envVars:
      - key: TELEGRAM_TOKEN
        sync: false
      - key: TELEGRAM_CHAT_ID
        sync: false
      - key: TIKTOK_COOKIES_B64
        sync: false
    healthCheckPath: /ping